### ISSUE TITLE
Possible error in gap/overlap calculation?

### ISSUE THREAD

**Issue by telecoder** [EarthScope/msi#2]
Considering the miniseed file resulting from:
`curl "http://service.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=TDHS&cha=BNZ&loc=20&start=2016-09-01T04:59:50&end=2016-09-01T05:00:00" -o hola.mseed`

This file contains only 2 miniseed packets that msi  considers to be continuous, and snuffler seems to agree:

```
$ msi -g hola.mseed
NZ_TDHS_20_BNZ, 166456, D, 512, 664 samples, 50 Hz, 2016,245,04:59:37.634613
NZ_TDHS_20_BNZ, 166457, D, 512, 661 samples, 50 Hz, 2016,245,04:59:50.913666
   Source                Last Sample              Next Sample       Gap  Samples
Total: 0 gap(s)

```
Considering that the sample rate is 50 Hz, I think the second packet should start at **2016,245,04:59:50.914613.**

I can't decide where the error is, is it the data, msi ... or my understanding?

Thanks.

**Comment by chad-earthscope** [comment]
Re-doing your work just to check, which agrees:
Sample period = 1/50 = 0.02
Time of expected next sample: 2016,245,04:59:37.634613 + (664 * 0.02) seconds
2016,245,04:59:37.634613 + 13.28 = **2016,245,04:59:50.914613**

The difference between the actual next sample and expected next sample is: 
50.914613 - 50.913666 = 0.000947 seconds.

The default time tolerance for libmseed (used by msi) is 1/2 sample period, which is quite large.
For 50 sps, 0.02 seconds, that's 0.01 seconds.

So, the time difference was within tolerance, therefore a single trace.

`msi` has time tolerance option to override the default (`-tt`).  If you set that to `0`, you'll see the small time difference.

Details: The reality of recorded data is that accuracy of time stamps and/or sample rates vary, sometimes very slightly over long periods of time (think free clock oscillator running at 49.9999 Hz), sometimes in jumps (think GPS clock re-sync after some period of being out of sync).  Since each miniSEED record only has a single time stamp and then a sample rate, it can only represent a (small) series of samples at a single rate, of course if the time stamp or rate is not right or changes during the record, the calculated time of samples will be (usually slightly) wrong.  When the time stamps and/or rate varies as described a result is often that there are small difference between records, a time "jitter".  The re-construction of a time series from the snippets represented in miniSEED is up to the software being used.  In most libmseed-based tools like `msi`, the start time is tracked from the first record and the end time is tracked as calculated from the last record.  This, in effect, smooths the variation over the whole series.  If the variation is significant the noted sample rate will likely be incorrect for the series, and should be recalculated, which is rarely done by software automatically, as it's rare for significant error to accumulate.

**Comment by telecoder** [comment]
Thank you very much for such a detailed explanation!
